module.exports = {
    DEFAULT_OFFSET: 0,
    DEFAULT_LIMIT: 30,
    DEFAULT_DIRECTION: 'ASC',
    DEFAULT_FIELD: 'id',
    RESOURCE_DELETED: 'Resource deleted successfully',
    RESOURCE_UPDATED: 'Resource updated successfully',
    RESOURCE_NOT_FOUND: 'The resource was not found',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    TITLE_ALREADY_EXIST: 'The title already exist',
    SERVER_RUNNING: 'Server running in ',
    BAD_CREDENTIALS: 'Invalid credentials',
    CAN_NOT_GENERATE_TOKEN: 'Can not generate the token',
    TOKEN_INVALID: 'The x-token is not valid',
    EMAIL_REQUIRED: 'The email is required',
    EMAIL_INVALID: 'The email is invalid',
    PASSWORD_REQUIRED: 'The password is required',
    ID_INVALID: 'The id is not valid',
    TITLE_REQUIRED: 'The title is required',
    TITLE_SHORT: 'The title must not exceed 64 characters',
    PRICE_REQUIRED: 'The price is required',
    PRICE_INVALID: 'The price must be a number',
    STATUS_INVALID: 'The status must be true or false',
    USER_DEFAULT_CREATED: 'User default created'
};